// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWysM1IJgLwzqBJxxszAIys5U74vWWnv0',
    appId: '1:145848950294:web:527d77a6fc85fab4579f37',
    messagingSenderId: '145848950294',
    projectId: 'shopease-sprints',
    authDomain: 'shopease-sprints.firebaseapp.com',
    storageBucket: 'shopease-sprints.firebasestorage.app',
    measurementId: 'G-SCEHBDV9E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu88TSD-LMb-dsZ5_Mti-9jXDDy5K3lbo',
    appId: '1:145848950294:android:469cf424f3cfa4f6579f37',
    messagingSenderId: '145848950294',
    projectId: 'shopease-sprints',
    storageBucket: 'shopease-sprints.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqazbBiDOcbkx8giGET6YLXxcvKumk0pI',
    appId: '1:145848950294:ios:2aaf385b0e260c1d579f37',
    messagingSenderId: '145848950294',
    projectId: 'shopease-sprints',
    storageBucket: 'shopease-sprints.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqazbBiDOcbkx8giGET6YLXxcvKumk0pI',
    appId: '1:145848950294:ios:2aaf385b0e260c1d579f37',
    messagingSenderId: '145848950294',
    projectId: 'shopease-sprints',
    storageBucket: 'shopease-sprints.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWysM1IJgLwzqBJxxszAIys5U74vWWnv0',
    appId: '1:145848950294:web:5b92d95877a1b1aa579f37',
    messagingSenderId: '145848950294',
    projectId: 'shopease-sprints',
    authDomain: 'shopease-sprints.firebaseapp.com',
    storageBucket: 'shopease-sprints.firebasestorage.app',
    measurementId: 'G-QE5B70ZZ9N',
  );
}
